# Generated by Django 4.2 on 2023-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=100, null=True)),
                ('cdescription', models.CharField(blank=True, max_length=200, null=True)),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
