# Generated by Django 4.2 on 2023-06-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catdb',
            old_name='cdescription',
            new_name='cdes',
        ),
    ]
