# Generated by Django 4.2 on 2023-06-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0002_rename_cdescription_catdb_cdes'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pselect', models.CharField(blank=True, max_length=100, null=True)),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('pdes', models.CharField(blank=True, max_length=100, null=True)),
                ('pprice', models.CharField(blank=True, max_length=100, null=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='vechicles')),
            ],
        ),
    ]
