# Generated by Django 4.2 on 2023-07-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartbd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=100, null=True)),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('pdes', models.CharField(blank=True, max_length=100, null=True)),
                ('pqu', models.CharField(blank=True, max_length=100, null=True)),
                ('pprice', models.CharField(blank=True, max_length=100, null=True)),
                ('ptotal', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
