# Generated by Django 4.2 on 2023-07-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_cartbd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbd',
            name='ptotal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
