# Generated by Django 4.2 on 2023-07-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_billdb_alter_cartbd_ptotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbd',
            name='ptotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
